String verbo[] = {
  "Analisamos", 
  "Armazenamos", 
  "Avaliamos", 
  "Coletamos", 
  "Combatemos", 
  "Compartilhamos", 
  "Conectamos", 
  "Detectamos", 
  "Distinguimos", 
  "Enviamos", 
  "Fornecemos", 
  "Garantimos", 
  "Gravamos", 
  "Identificamos", 
  "Informamos", 
  "Mantemos", 
  "Mostramos", 
  "Obtemos", 
  "Otimizamos", 
  "Permitimos", 
  "Personalizamos", 
  "Prevenimos", 
  "Processamos", 
  "Publicamos", 
  "Recebemos", 
  "Recolhemos", 
  "Reconhecemos", 
  "Registramos", 
  "Respondemos", 
  "Salvamos", 
  "Solicitamos", 
  "Usamos"};

String objeto[] = {
  "o nome de usuário", 
  "a data de nascimento", 
  "o número de telefone", 
  "a foto do perfil", 
  "o gênero", 
  "os seguidores", 
  "a agenda de contatos", 
  "o número de quem recebe chamada", 
  "o horário da chamada", 
  "a duração da chamada", 
  "o cartão de crédito", 
  "os detalhes da cobrança", 
  "os lugares que frequenta", 
  "as rotas de viagem", 
  "os horários de filmes que estão próximos", 
  "a localização atual", 
  "onde mora", 
  "empresas próximas", 
  "os metadados das imagens", 
  "o áudio gravado", 
  "os vídeos", 
  "suas mensagens", 
  "o conteúdo gerado", 
  "os conteúdos salvos", 
  "o comportamento nas operações", 
  "as reações de engajamentos", 
  "a interação com os usuários", 
  "quais são os seus interesses", 
  "as preferências de interação", 
  "que poderá interessar no futuro", 
  "o histórico de navegação", 
  "o tempo de acesso", 
  "a frequência de uso", 
  "o movimento do cursor", 
  "as janelas em segundo plano", 
  "anúncios visualizados", 
  "o site que visitou", 
  "experiência negativa", 
  "a compra feita", 
  "a transação realizada", 
  "quais jogos você joga", 
  "parceiros de marketing e parceiros de segurança", 
  "a eficácia dos anúncios", 
  "para fins de publicidade", 
  "campanha direcionada", 
  "nosso produto", 
  "nosso serviço", 
  "nossa plataforma", 
  "nosso negócio", 
  "o melhor design do produto", 
  "estatísticas agregadas", 
  "automaticamente", 
  "algoritmos de malware e conteúdo ilegal", 
  "parceiros de terceiros", 
  "desenvolvedores", 
  "parceiros externos", 
  "informações de anunciantes", 
  "a sua rede social", 
  "cookies e tecnologias semelhantes", 
  "pelo reconhecimento facial", 
  "o modelo do dispositivo", 
  "a resolução da tela", 
  "o sistema operacional", 
  "os computadores conectados", 
  "anúncios em seu telefone", 
  "as televisões conectadas", 
  "o nível de bateria", 
  "a força do sinal", 
  "o espaço de armazenamento disponível", 
  "o sinal de Bluetooth", 
  "o ponto de acesso de WiFi", 
  "as torres de celular", 
  "a câmera e filtros", 
  "com precisão pelo GPS do dispositivo móvel", 
  "a operadora de internet", 
  "o fuso horário", 
  "o endereço IP", 
  "a velocidade de conexão", 
  "os relatórios de erros", 
  "as fraudes", 
  "os abusos", 
  "os riscos de segurança", 
  "problemas técnicos", 
  "os problemas encontrados", 
  "padrões nos dados", 
  "a última vez acessada", 
  "humanos de bots", 
  "atividades suspeitas", 
  "violações de nossos termos", 
  "que outras contas vejam quem viu", 
  "fortes restrições", 
  "os tipos de pessoas que visualizaram", 
  "relatórios de mensuração", 
  "com autoridades responsáveis", 
  "pela aplicação da lei", 
  "termos que você pesquisa", 
  "ações online e offline", 
  "upload ou download de conteúdo", 
  "várias tecnologias", 
  "categorias sensíveis", 
  "diretamente com você", 
  "segurança e confiabilidade", 
  "sistemas automatizados", 
  "sua autorização", 
  "bem-estar social geral", 
  "sua atividade em todos os dispositivos", 
  "o que você vê", 
  "o que outras pessoas fornecem", 
  "independentemente de ter ou não uma conta", 
  "provedores de dados de terceiros", 
  "por seu intermédio", 
  "produtos relevantes para você", 
  "você em fotos e vídeos", 
  "para ajudar os anunciantes", 
  "conduta danosa"
};
